tarball=exceptiongroup-VERSION-py3-none-any.whl
sha1=e69c438e6d15111c4f7cc18224b31a42a58663da
md5=d252c64173c449dc34654e7be8211744
cksum=527795480
upstream_url=https://pypi.io/packages/py3/e/exceptiongroup/exceptiongroup-VERSION-py3-none-any.whl
